name: lambda_calculus_front_end
description: Lambda Calculus Simulator.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_markdown: ^0.6.18
  lambda_calculus: ^1.3.3
  markdown: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: monospace
      fonts:
        - asset: fonts/RobotoMono-Regular.ttf
        - asset: fonts/RobotoMono-Italic.ttf
          style: italic
